function SessionSettings = sessionSettings(exp_type, texture_params, luminance, contrast, stimulus_size, target_radius, edgePowerBlockEdges, monitor_distance, transformExpName)
%SESSIONSETTINGS Loads settings and stimuli for each experimental session 
% 
% Example: 
%  ExpSettings = SESSIONSETTINGS([5 5 5], linspace(0.05, 0.2, 5)); 
%
% Output: 
%  ExpSettings Structure containing stimuli and experiment settings
%
% See also:
%   LOADSTIMULIADDITIVE
%
% v1.0, 1/22/2016, Steve Sebastian <sebastian@utexas.edu>
% v1.1, 2/4/2016,  R. Calen Walshe <calen.walshe@utexas.edu> Added
% peripheral settings.

stimulusIntervalMs = 200;
responseInvervalMs = 1000;
fixationIntervalMs = 100;
blankIntervalMs    = 0;

monitorMaxPix = 255;
bgPixVal = luminance*255;
monitor_brightness=50;
monitor_contrast=100;

nLevels = size(edgePowerBlockEdges,1);
nTrials = 30;
nSessions = 4;

% edgePowerBlockCenters=movmean(edgePowerBlockEdges,2,'Endpoints','discard');
edgePowerBlockCenters=mean(edgePowerBlockEdges,2);

stimPosDeg = zeros(nTrials, nLevels, nSessions, 2);
fixPosDeg = zeros(nTrials, nLevels, nSessions, 2);

loadSessionStimuli = @experiment.loadStimuliCamouflage;
pTarget = .5;

if strcmp(transformExpName','')
    % generate new stimuli    
    bTargetPresent = logical(experiment.generateTargetPresentMatrix(nTrials, nLevels, nSessions, pTarget));
    [stimuli, seeds, edgePowers, pClipped] = experiment.generate_camouflage_stimuli(texture_params,exp_type,edgePowerBlockEdges,nTrials,nSessions,stimulus_size,target_radius,luminance,contrast,bTargetPresent);
else
    % transform stimuli of existing experiment
    [stimuli, seeds, edgePowers, pClipped, bTargetPresent] = experiment.transform_camouflage_stimuli(transformExpName,luminance,contrast);
end

SessionSettings = struct(...
    'exp_type', exp_type,...
    'texture_params', texture_params,...
    'luminance', luminance,...
    'contrast', contrast,...
    'target_radius', target_radius,...    
    'stimulus_size', stimulus_size,...
    'monitor_distance', monitor_distance,...
    'nLevels', nLevels,...
    'nTrials', nTrials,...
    'nSessions', nSessions, ...
    'pTarget', pTarget,...    
    'loadSessionStimuli', loadSessionStimuli, ...
    'bTargetPresent', bTargetPresent,...
    'edgePowerBlockEdges', edgePowerBlockEdges,...
    'edgePowerBlockCenters',edgePowerBlockCenters,...
    'edgePowers', edgePowers,...    
    'seeds', seeds,...
    'stimuli', stimuli,...
    'pClipped', pClipped,...
    'moniter_brightness', monitor_brightness,...
    'monitor_contrast', monitor_contrast,...
    'stimPosDeg', stimPosDeg, ...
    'fixPosDeg', fixPosDeg,...
    'monitorMaxPix', monitorMaxPix, ...
    'bgPixVal', bgPixVal, ...
    'stimulusIntervalMs', stimulusIntervalMs,...
    'responseIntervalMs', responseInvervalMs, ...
    'fixationIntervalMs', fixationIntervalMs,...
    'blankIntervalMs', blankIntervalMs...
    );  
    
end
