function SessionSettings = sessionSettings_all(luminance, contrast, stimulus_size, target_radius, ppd)
%SESSIONSETTINGS Loads settings and stimuli for each experimental session
%
% Example:
%  ExpSettings = SESSIONSETTINGS([5 5 5], linspace(0.05, 0.2, 5));
%
% Output:
%  ExpSettings Structure containing stimuli and experiment settings
%
% See also:
%   LOADSTIMULIADDITIVE
%
% v1.0, 1/22/2016, Steve Sebastian <sebastian@utexas.edu>
% v1.1, 2/4/2016,  R. Calen Walshe <calen.walshe@utexas.edu> Added
% peripheral settings.


stimulusIntervalMs = 200;
responseInvervalMs = 1000;
fixationIntervalMs = 100;
blankIntervalMs    = 0;

monitorMaxPix = 255;
bgPixVal = luminance*255;
monitor_brightness=50;
monitor_contrast=100;

% load texture list
load('exp_files/all/texture_list.mat');
nTex=length(texture_list);

nTrials_eachtx=40;

nLevels = 10;
nSessions = 4;
nTrials = nTex*nTrials_eachtx/(nLevels*nSessions);

stimPosDeg = zeros(nTrials, nLevels, nSessions, 2);
fixPosDeg = zeros(nTrials, nLevels, nSessions, 2);

loadSessionStimuli = @experiment.loadStimuliCamouflage;
pTarget = .5;


% generate stimuli
[stimuli, textures, seeds, bTargetPresent, pClipped] = experiment.generate_camouflage_stimuli_all(texture_list,nTex,nTrials_eachtx,nTrials,nLevels,nSessions,stimulus_size,target_radius,luminance,contrast);

SessionSettings = struct(...
    'exp_type', 'all',...
    'textures', textures,...
    'luminance', luminance,...
    'contrast', contrast,...
    'target_radius', target_radius,...
    'stimulus_size', stimulus_size,...
    'monitor_distance', ppd,...
    'nTrials_eachtx', nTrials_eachtx,...
    'nLevels', nLevels,...
    'nTex', nTex,...
    'nTrials', nTrials,...
    'nSessions', nSessions, ...
    'pTarget', pTarget,...
    'loadSessionStimuli', loadSessionStimuli, ...
    'bTargetPresent', bTargetPresent,...
    'seeds', seeds,...
    'stimuli', stimuli,...
    'pClipped', pClipped,...
    'moniter_brightness', monitor_brightness,...
    'monitor_contrast', monitor_contrast,...
    'stimPosDeg', stimPosDeg, ...
    'fixPosDeg', fixPosDeg,...
    'monitorMaxPix', monitorMaxPix, ...
    'bgPixVal', bgPixVal, ...
    'stimulusIntervalMs', stimulusIntervalMs,...
    'responseIntervalMs', responseInvervalMs, ...
    'fixationIntervalMs', fixationIntervalMs,...
    'blankIntervalMs', blankIntervalMs...
    );

end
