function setUpExperiment(exp_type)
% Create experimental stimuli and settings

nTex=60; % number of textures
nTrials=10; % number of trials for each texture pair
nLevels=4; % number of eccentricity levels
nSessions=4; % number of sessions to divide this into.

stimPosDeg = zeros(nTrials, nLevels, nSessions, 2);
fixPosDeg = zeros(nTrials, nLevels, nSessions, 2);

% generate stimuli
[stimuli, idx, seeds, tex, coords]=experiment.generate_stimuli();

% experiment settings
exp_settings = struct(...
    'exp_type', exp_type,...
    'nTex', nTex,...
    'nLevels', nLevels,...
    'nTrials', nTrials,...
    'nSessions', nSessions, ...
    'loadSessionStimuli', @experiment.loadStimuli, ...
    'stimuli', stimuli,...
    'idx', idx,...
    'tex', tex,...
    'coords', coords,...
    'seeds', seeds,...
    'stimPosDeg', stimPosDeg, ...
    'fixPosDeg', fixPosDeg,...
    'luminance', 0.5,...
    'contrast', 0.15,...
    'ppd', 60,...
    'moniter_brightness', 50,...
    'monitor_contrast', 100,...
    'monitorMaxPix', 255, ...
    'bgPixVal', 0.5*255, ...
    'stimulusIntervalMs', 200,...
    'responseIntervalMs', 1000, ...
    'fixationIntervalMs', 100,...
    'blankIntervalMs', 0 ...
    );

folderOut= ['exp_files/' exp_type];
mkdir(folderOut);
fpOut = [folderOut '/exp_settings.mat'];
save(fpOut, 'exp_settings');

%% Subject experiment files

nSubjects = size(subjectStr, 1);

for iSubject = 1:nSubjects
    SubjectExpFile = experiment.subjectExperimentFile(exp_settings);
    folderOut= ['exp_files/' exp_type '/subject_out'];
    mkdir(folderOut);
    fpOut = [folderOut '/' subjectStr(iSubject,:) '.mat'];
    save(fpOut, 'SubjectExpFile');
end
end
